### ISSUE TITLE
Make Use Case Diagram

### ISSUE THREAD

**Issue by YSJL** [wkim345/GameSuite#11]

**Comment by gosbhs12** [comment]
- A set of typical scenarios of using a system
- Primarily for functional requirements

**Comment by gosbhs12** [comment]
<img width="1004" alt="Screen Shot 2022-05-25 at 2 59 34 PM" src="https://user-images.githubusercontent.com/72944128/170347710-a44af883-9ac9-47a0-befc-b692beddead1.png">
